### ISSUE TITLE
Permission denied when installing it on Debian Buster

### ISSUE THREAD

**Issue by mirelsol** [danburzo/percollate#102]
### Environment

* Operating System: Debian Buster
* `node --version`: 14.9.0
* `npm --version`: 6.14.8
* `yarn --version`, if using Yarn:  
* `percollate --version`: 1.0.1

### Description

When I execute : sudo npm install -g percollate, I got at some point :
```
/usr/bin/percollate -> /usr/lib/node_modules/percollate/cli.js

> puppeteer@5.2.1 install /usr/lib/node_modules/percollate/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r782078! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/percollate/node_modules/puppeteer/.local-chromium'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/percollate/node_modules/puppeteer/.local-chromium'
} 
```

**Comment by danburzo** [comment]
Thanks for the report! Are you behind a firewall, or blocking Google servers via your hosts file, or something to that tune? According to [this puppeteer issue](https://github.com/puppeteer/puppeteer/issues/2173), the Chromium build is fetched from the `https://storage.googleapis.com` domain, so whitelisting it (at least while you install percollate) might help. Alternatively, several people in that thread mention that something like this worked for them:

```bash
sudo npm install -g percollate --unsafe-perm=true --allow-root
```

Let me know if any of this helps!

**Comment by mirelsol** [comment]
Thanks for the quick answer! In fact this is not related to blocking Google servers nor being behind a firewall, because I also had this error : gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/percolate/node_modules/gc-stats/.node-gyp'.

But using `--unsafe-perm=true --allow-root` makes the install work. Thanks!

**Comment by danburzo** [comment]
Glad to hear! :-)
