### ISSUE TITLE
EPUB Metadata Support

### ISSUE THREAD

**Issue by captn3m0** [danburzo/percollate#104]
### Feature description

A flag to pass additional EPUB metadata, such as what is supported by pandoc's `--metadata` flag. This would let us provide details like additional authors/translators/illustrators/publisher/ISBN etc to the generated EPUB file.

### Existing workarounds

With some additional tooling - yes.

I generate metadata using [epub-metadata-generator](https://www.npmjs.com/package/epub-metadata-generator), then open the file in Sigil and copy/paste the additional details.

Maybe a `--isbn` flag that would fetch the metadata using the npm package?

**Comment by danburzo** [comment]
Hi @captn3m0, thanks for the report! (And sorry for the late reply, I was away from the computer last week). 

There is [a similar open issue for PDFs](https://github.com/danburzo/percollate/issues/88), and while for PDF we'd prefer some first-class support from Puppeteer/Chromium, in EPUBs we can potentially embed any metadata.

So I guess it's a matter of deciding _what_ metadata we allow and what the command-line options look like, keeping the following in mind:

* There's already the `--title` option to specify the publication's title
* The `--individual` flag will generate one file per input URL — how will the metadata apply to the files?

**Comment by captn3m0** [comment]
>The --individual flag will generate one file per input URL — how will the metadata apply to the files?

Applying everywhere sounds like the better deal, since these are likely common things. For non-common items (such as title), `--title` can be used for now?

Applying nowhere will result in the same problem - no way to add metadata. 

Or as a third alternative, mark `--metadata` flag as invalid in combination with `--individual`?

>So I guess it's a matter of deciding what metadata we allow

I like the `pandoc` approach of letting the user pass a valid XML file.

**Comment by danburzo** [comment]
Closing this for now. It seems unlikely that `percollate` will develop in the direction of allowing more than the basic metadata already added to PDFs and EPUBs, as it doesn't fit neatly in the scope of this tool.
