### ISSUE TITLE
Correct async behavior

### ISSUE THREAD

**Issue by yashha** [danburzo/percollate#106]
I think at the moment there are a few await declarations missing.
These should be corrected at some point.
https://github.com/danburzo/percollate/blob/c5192bc28728c6ed5752cc73d0d133bef248e1cd/index.js#L486

Also tests are missing where the pdf is generated and checked if the file exists afterwards.

Thank you, for continuing working on this project @danburzo! :)

**Comment by danburzo** [comment]
Ah yes, thanks for logging this — I was meaning to write it down. I definitely need to read through the execution and fix the little async flows, the logging also tends to be a bit chaotic as a result.
