### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by danburzo** [danburzo/percollate#11]

**Comment by phenax** [comment]
I'd like to work on this one.

**Comment by danburzo** [comment]
Perfect!

**Comment by phenax** [comment]
@danburzo Any objections to introducing mocha, chai as dev-dependencies and ramda as a dependency?

**Comment by danburzo** [comment]
@phenax I am okay with mocha / chai for the tests. What are your thoughts on introducing ramda in the codebase? If it's not absolutely necessary, I'd like to keep the code as approachable as possible, so people can fork the repo and implement their own version.

**Comment by danburzo** [comment]
Closing this for now, will add new tests incrementally.
