### ISSUE TITLE
Problems with website encoding iso-8859-1

### ISSUE THREAD

**Issue by yashha** [danburzo/percollate#118]
### Environment

* Operating System: 
* `node --version`: v14.11.0
* `npm --version`: 6.14.8
* `yarn --version`, if using Yarn:  
* `percollate --version`: 1.2.0

### Description

When converting a page with encoding of iso-8859-1 to pdf you'll get bad encoding symbols.

For example:
[Test-Page](http://www.zeno.org/Philosophie/M/Hegel,+Georg+Wilhelm+Friedrich/Enzyklop%C3%A4die+der+philosophischen+Wissenschaften+im+Grundrisse/Erster+Teil.+Die+Wissenschaft+der+Logik./2.+Abteilung%3A+Die+Lehre+vom+Wesen)
[API](https://api.readtheweb.de/load.pdf?pagesperside=1&url=http://www.zeno.org/Philosophie/M/Hegel,+Georg+Wilhelm+Friedrich/Enzyklop%C3%A4die+der+philosophischen+Wissenschaften+im+Grundrisse/Erster+Teil.+Die+Wissenschaft+der+Logik./2.+Abteilung%3A+Die+Lehre+vom+Wesen)

**Comment by danburzo** [comment]
Fixed in PR above, available in `percollate@v.1.2.2`. Thanks, @yashha!
