### ISSUE TITLE
Return retrieved data when using programmatically

### ISSUE THREAD

**Issue by yashha** [danburzo/percollate#122]
### Feature description

When you run percollate programmatically, it would be nice to get a nice result which contains the items, maybe with the full HTML and maybe the used options.

Example result:
```
{
	items: [{
		id: ""
		title: "",
		...,
		html: ""	
	}],
	options: {}
}
```

### Existing workarounds

Make a manual second call and parse the HTML.

**Comment by danburzo** [comment]
Awesome, thank you @yashha! Please note I changed the name of the property from `html` to `originalContent`.
