### ISSUE TITLE
Spawn unknown system error -86; node:internal/errors:464 – Puppeteer issue?

### ISSUE THREAD

**Issue by PapiPeppers** [danburzo/percollate#135]
### Environment

* Operating System: 
* `node --version`: 16.13.2
* `npm --version`: (pnpm) latest 
* `percollate --version`: 2.2.0

### Description
Ran into this error for the first time yesterday, seems to be internal to node or possibly puppeteer version 10.4.0. Attached file containing command and error message output and image of same info.

[percollate-issue.md](https://github.com/danburzo/percollate/files/8127714/percollate-issue.md)
![image](https://user-images.githubusercontent.com/57047860/155406113-3823e071-f856-4bee-a8f3-37c4f943fdf4.png)

**Comment by danburzo** [comment]
Thanks for the report. Poking around GitHub it sounds like the error may be related to running Puppeteer on an Apple M1 chip: 

- https://github.com/pa11y/pa11y/issues/619

Have you recently migrated to an M1 machine, or enabled/disabled Rosetta for running Intel-based apps?

**Comment by PapiPeppers** [comment]
No recent changes. I've been using percollate daily on an m1 mini for months now. I'll double check Rosetta.

**Comment by PapiPeppers** [comment]
You were right. It was a rosetta issue – I needed to reinstall rosetta, might have been my own error or recent beta update that removed rosetta. Everything works as expected now. Thanks!

**Comment by danburzo** [comment]
Glad to hear everything is in order!

**Comment by forthrin** [comment]
When will this be independent of Rosetta? Or is there another open source CLI tool that prints webpages on Silicons?
