### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by kouroshshafi** [danburzo/percollate#138]
Feature Request

Is that possible to use the fetched url after this paywall-bypass chrome extension https://github.com/iamadamdev/bypass-paywalls-chrome
?

I really appreciate if you have suggestions into integration percollate with paywall-bypass.

Thanks

**Comment by danburzo** [comment]
Hi @kouroshshafi, thanks for the report!

Integration with other browser extensions will only be possible if/when percollate has a browser extension of its own. The issue is tracked here: 

- https://github.com/danburzo/percollate/issues/60

**Comment by danburzo** [comment]
As a workaround, if you are able to save a webpage as HTML to your disk, you can use the `--url` option to supply the original URL:

```bash
percollate pdf my-file.html --url=https://<original-url>/
```
