### ISSUE TITLE
Nested <pre> breaks page enhancement

### ISSUE THREAD

**Issue by UddipakBhuyan** [danburzo/percollate#165]
### Environment

* Operating System: Arch Linux (6.7.0-arch3-1)
* `node --version`: v21.6.0
* `npm --version`: 10.3.0
* `yarn --version`, if using Yarn:  1.22.21
* `percollate --version`: 4.0.4

### Description

For [rust lang reference book](https://doc.rust-lang.org/reference/print.html), percollate seems to fail with null error. Please find logs in attached file.
[bug_log_file.txt](https://github.com/danburzo/percollate/files/13977876/bug_log_file.txt)

Command ran:
`percollate --debug epub https://doc.rust-lang.org/reference/print.html`

Thanks.

**Comment by danburzo** [comment]
Thanks for the bug report. The error seems to originate from the `wrapPreBlocks` enhancement, probably due to the use of nested `<pre>` elements on the page.

**Comment by danburzo** [comment]
Fixed in [`percollate@4.0.5`](https://github.com/danburzo/percollate/releases/tag/v4.0.5)
