### ISSUE TITLE
Can I convert an HTML into an epub and automatically generate a table of contents with the H2 headings?

### ISSUE THREAD

**Issue by jinshuqishi2019** [danburzo/percollate#167]
### Feature description

Can I convert an HTML into an epub and automatically generate a table of contents with the H2 headings?

**Comment by danburzo** [comment]
We could probably add a `--toc-level` option to control how deep the table of contents of the generated document should be.

**Comment by danburzo** [comment]
Released `--toc-level` as part of [`percollate@v4.1.1`](https://github.com/danburzo/percollate/releases/tag/v4.1.1).
