### ISSUE TITLE
Text only output

### ISSUE THREAD

**Issue by winstonma** [danburzo/percollate#181]
First thanks for the package. I really like it.

### Feature description
I would like to feed the article to [edge-tts](https://github.com/rany2/edge-tts) with text only (remove image url and heading) as listener would listen to the text only. The following code would be my desired demo:

```bash
# Just a demo url
ARTICLE_URL="https://stratechery.com/2024/integration-and-android/"
# Output the result on screen
percollate text -o - $ARTICLE_URL | cat
```

Thank again for this package

### Existing workarounds
I am using [pandoc](https://pandoc.org/) to convert markdown to text

```bash
# Just a demo url
ARTICLE_URL="https://stratechery.com/2024/integration-and-android/"
# Output the result on screen
percollate md -o - $ARTICLE_URL | pandoc -t plain | cat
```

The output is, due to pandoc conversion, was outputted as multiple lines. When the text is fed into edge-tts the audio would be spoken with weird gap.

_Is there any way to obtain the desired effect with the current functionality?_

**Comment by danburzo** [comment]
Hi @winstonma! My idea around supporting Markdown was that percollate would be used along other tools for further processing, and piping into `pandoc` is exactly the kind of thing that I would expect for converting to plain text. I understand, however, that its plain-text formatter produces hard-wrapped paragraphs which, as you said, are unsuitable for TTS.

I wrote a separate CLI tool for handling HTML/MD/Plain text called [`trimd`](https://github.com/danburzo/trimd). Its output may be closer to what you’re looking for. You may try either `percollate html | trimd demarkup` for HTML to text or `percollate md | trimd demarkdown` for MD to text.

**Comment by winstonma** [comment]
Thanks a lot. I think the pure text output is better than pandoc. That's works in my scenario. Thanks again for your tool.
