### ISSUE TITLE
Screenshots to README

### ISSUE THREAD

**Issue by hello-w0r1d** [danburzo/percollate#32]
Hi,

Good work on this one!
It would be nice to include a few screenshots on the README page just to get a brief idea of what the output would look like.

Regards.

**Comment by migben** [comment]
I think @danburzo is addressing this or something similar. 

https://github.com/danburzo/percollate/issues/29

**Comment by danburzo** [comment]
@hello-w0r1d that's a great suggestion. As @migben mentioned, it's already covered by #29, but I'll admit it doesn't have the greatest issue title :-)
