### ISSUE TITLE
Transform static html folders ?

### ISSUE THREAD

**Issue by revskill10** [danburzo/percollate#34]
Let's say we have a static web site which is generated by a static site generator.
Could we transform them into one pdf ?

**Comment by danburzo** [comment]
In theory, we should be able to do something like this:
```bash
percollate pdf --output ~/Downloads/test.pdf **/*.html
```

Where the `**/*.html` glob pattern will match all HTML files, recursively, in the current directory. However, right now `percollate` assumes the paths are URLs, not local files. Once we sort it out, it should definitely be possible.

**Comment by revskill10** [comment]
Two of things i'm concerned about are:
- Nice table of contents based on directory structure of generated static site.
- Nice handling of paging and break between pages.

**Comment by danburzo** [comment]
percollate can now work with local files (with or without the `file://` protocol). Table of Contents generation is currently linear, based on the order of the files provided.
