### ISSUE TITLE
Output multiple PDF files for multiple webpages instead of one single PDF?

### ISSUE THREAD

**Issue by x-ji** [danburzo/percollate#38]
As discussed in https://github.com/danburzo/percollate/issues/37, sometimes it might be useful to output each webpage to a separate PDF instead of putting all pages into one PDF.

**Comment by danburzo** [comment]
I wonder if this can be achieved with standard UNIX commands to keep `percollate` itself simpler...

**Comment by danburzo** [comment]
@x-ji what would be your preferred flow here, in terms of running the command(s)? Would you get the URLs from browser tabs and paste them in the command line? would you keep them in a separate file?

**Comment by x-ji** [comment]
That's a good point. Though #40 looks quite good. Thanks a lot for this. I'd most likely keep the URLs in a separate file, but for now I can also feed the file content to the command line with something like `percollate pdf $(< ~/list)`

**Comment by danburzo** [comment]
The `--individual` flag is available in `percollate@0.2.10`

**Comment by x-ji** [comment]
Yeah. I was just describing a way to pass in the webpages to download via a file, whether the `--individual` flag is passe in or not.

The version works perfectly. Thanks :heart:
