### ISSUE TITLE
Usecases for --stylesheet vs. --css handling in the HTML template

### ISSUE THREAD

**Issue by danburzo** [danburzo/percollate#51]
Initially, the HTML template received the path for the stylesheet (either the default one, or a custom one provided with the `--stylesheet` option):

https://github.com/danburzo/percollate/blob/7c43aec36d94476fcaa31d136fcebd053d70f87e/templates/default.html#L3-L7

With the introduction of the `--css` option, I changed it to:

https://github.com/danburzo/percollate/blob/cecd11e0c290d0bd0b653047c53e2f82bfb31fca/templates/default.html#L7-L9

And deprecated the passing of the `stylesheet` property to the template.

However, I think I might have missed a valid use-case for an external stylesheet, namely being able to reference outside resources (images, web fonts) in the custom CSS.

This issue outline some use-cases, to make sure the final solution covers all of them elegantly:

* [x] __Override just the page size, margins, font sizes__
* [x] __Override the default stylesheet with a custom one__
* [x] __Use local web fonts__ in the custom stylesheet

(Adding to this list as more use-cases arise)

**Comment by x-ji** [comment]
Actually I wonder how I can change the default font. In my case a sans-serif font aids my reading more. I tried passing in `font-family: "Noto Sans"` or `font-family: sans-serif` with the `--css` argument but that didn't seem to work.

**Comment by x-ji** [comment]
OK apparently I was stupid and should have specified the `font-family` option under `html { }` instead of `@page { }`.

**Comment by danburzo** [comment]
Added an example here: https://github.com/danburzo/percollate#the---css-option

**Comment by danburzo** [comment]
> Override just the page size, margins, font sizes

This works well with the `--css` option.

> Override the default stylesheet with a custom one.

This works via the `--style` option.

> Use local web fonts.

For PDFs and HTMLs you can either reference fonts by name with `local()`, or use their absolute path on disk. EPUBs currently don't fetch these fonts to bundle them, but that's okay.

I think we can close the issue for now.
