### ISSUE TITLE
noUselessHref: provide option to remove all hrefs

### ISSUE THREAD

**Issue by abelkov** [danburzo/percollate#54]
#31 Introduced some href filtering, but I wonder - do we really need to show those hrefs at all? I think they just make it harder to read the text.

Please provide an option to skip all href generation. For now I'm using this hack:

```
function noUselessHref(doc) {
	Array.from(doc.querySelectorAll(`a`))
		.filter(function(el) {
			return true;
		})
		.forEach(el => el.classList.add('no-href'));
}
```

**Comment by danburzo** [comment]
The idea with the hrefs was to produce PDFs that could be printed without losing where the links point to. However, I agree in some link-heavy contexts, this can be bothersome. 

The easiest way to achieve this is with the `--css` option:

```bash
percollate pdf --css "a:after { display: none }
```

(I'm not at the computer right now, but it should work. I'll also add it to the README.)
