### ISSUE TITLE
Images not included in the output PDF even though they are shown in Firefox reader view?

### ISSUE THREAD

**Issue by x-ji** [danburzo/percollate#58]
Seems to be a special case though for the page https://betterwebtype.com/rhythm-in-web-typography, the images are not displayed in the final PDF, even though they seem to show up fine in my Firefox's reader view. Any idea why?

**Comment by danburzo** [comment]
Ah, good catch! Looking at the [temporary HMTL] I could see that the images use the `<picture>` element and the `<source>` children are not resolved to absolute URLs. This should be fixable.
