### ISSUE TITLE
Some websites return 405 error

### ISSUE THREAD

**Issue by x-ji** [danburzo/percollate#59]
Some websites like SCMP (e.g. https://www.scmp.com/economy/china-economy/article/2169378/xi-jinping-donald-trump-agree-talks-g20-summit-next-month) doesn't seem to allow requests from headless browsers? I wonder if there's anything that can be done about it, though of course this might fall out of the scope of what this tool should handle.

**Comment by danburzo** [comment]
It seems to have been a problem with not supplying a User-Agent header. The change will be released soon!

**Comment by danburzo** [comment]
Released `percollate@0.2.13` which includes a fix for this issue.

**Comment by x-ji** [comment]
Thanks. Works well now.
