### ISSUE TITLE
Images are not rendered for specific article

### ISSUE THREAD

**Issue by mcdado** [danburzo/percollate#62]
`percollate pdf https://hpbn.co/primer-on-latency-and-bandwidth/`

Generates this: 
[Networking-101:-Primer-on-Latency-and-Bandwidth-High-Performance-Browser-Networking-(O'Reilly).pdf](https://github.com/danburzo/percollate/files/2500758/Networking-101.-Primer-on-Latency-and-Bandwidth-High-Performance-Browser-Networking-.O.Reilly.pdf)

Some of the image tags have `svg` sources, and they are not rendered. This page also has a `png` which is not rendered either.

**Comment by danburzo** [comment]
Hi, thanks for reporting! Can you let me know your percollate version by running `percollate --version`? It seems to be working for me on `0.2.12` / macOS.

**Comment by mcdado** [comment]
```
$ percollate --version
0.2.12
```

Could it be related to something else then? 🤔

**Comment by danburzo** [comment]
_Sorry, the Github downtime is making it hard to respond_. 

I've just published `percollate@0.2.13`. Can you try upgrading to see if the issue still reproduces? If it does, can you perhaps look at the [temporary html file](https://github.com/danburzo/percollate/blob/master/CONTRIBUTING.md#debugging-the-temporary-html) to see how the HTML markup around images looks? (or you can attach it here, I think, as a `.zip` file)

**Comment by mcdado** [comment]
Works perfectly! Thanks!
