### ISSUE TITLE
Maven documentation to pdf few code section missing

### ISSUE THREAD

**Issue by proful** [danburzo/percollate#66]
URL:- https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html
The below code snippet is not coming in the output pdf.
`mvn --version`
However, another code snippet appearing properly
`Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)`
![image](https://user-images.githubusercontent.com/354596/47339163-16508d00-d6e6-11e8-872b-a1f10d96d555.png)

![image](https://user-images.githubusercontent.com/354596/47339208-3da75a00-d6e6-11e8-9690-00d393183043.png)

**Comment by danburzo** [comment]
Yep, it's an issue in Readability. Tagged with _Phase: Readability_ to keep track of it. We may end up spinning our own Reader View that's more generous with leaving content in.

**Comment by butu5** [comment]
Took some time for me to fix this in readability.

![image](https://user-images.githubusercontent.com/354596/47498025-c02b4780-d8a7-11e8-8c09-1c078e62d200.png)

https://github.com/butu5/percollate/commit/94bd0773d2ec06b48641311dac674b4797e03a86#r31042606

```javascript
var pre = node.getElementsByTagName('pre').length;
if (pre > 0) return false
```

**Comment by danburzo** [comment]
Closing this in favor of the upstream issue at [mozilla/readability#374](https://github.com/mozilla/readability/issues/374).
