### ISSUE TITLE
Some ideas / suggestions

### ISSUE THREAD

**Issue by olivmonnier** [danburzo/percollate#78]
Hi, 
I have some ideas/packages npm to suggest you if you like:
- [mozilla/fathom](https://github.com/mozilla/fathom): instead of readability
- [pagedjs](https://gitlab.pagedmedia.org/tools/pagedjs): Build a TOC + header + footer pdf
- I work in press media and often we send to our clients a responsive email with the article content. This could be great to add this feature with for example [inky](https://foundation.zurb.com/emails/docs/inky.html)

An example of fathom who detect the best title web page:
```javascript
const { rule, ruleset, dom, out, score, type } = require('fathom-web');
const JSDOM = require('jsdom').JSDOM;
const vdom = new JSDOM(`
<html>
  <head>
    <title>Hello World</title>
    <meta property="og:title" content="Foo Bar Baz" />
  </head>
</html>
`).window.document;
const rules = ruleset(
  // Give any title tag the (default) score of 1, and tag it as title-ish:
  rule(dom('title'), type('titley')),

  // Give any OpenGraph meta tag a score of 2, and tag it as title-ish as well:
  rule(dom('meta[property="og:title"]'), type('titley').score(2)),

  // Take all title-ish things, and punish them if they contain
  // navigational claptrap like colons or dashes:
  // rule(type('titley'), score(fnode => containsColonsOrDashes(fnode.element) ? .5 : 1)),

  // Offer the max-scoring title-ish node under the output key "BestTitle":
  rule(type('titley').max(), out('BestTitle'))
);
const facts = rules.against(vdom);
const bestTitleFnode = facts.get('BestTitle');

bestTitleFnode.forEach(fnode => console.log(fnode))
```

Best regards

**Comment by danburzo** [comment]
Thank you, Olivier. These are very good suggestions! 

I've been meaning to add `fathom` to the [See also](https://github.com/danburzo/percollate#see-also) section of the readme. I was aware of its existence, but I was not sure what the status was on it, and whether it's ready for prime time. Seems like it is, though. I may be able to scrap my [work-in-progress here](https://github.com/danburzo/gullible-readability).

As for pagedjs, I haven't had the time yet to dig deeper into it. What I'm concerned about here is that the content fragmentation (splitting things across pages) may not be as robust as what the browser does natively, but I was extremely excited when I learned about it, and hope to have the chance to play with it soon.
