### ISSUE TITLE
Document setup on Windows 10

### ISSUE THREAD

**Issue by baddate** [danburzo/percollate#79]
how does it work on Win10

**Comment by danburzo** [comment]
Hi @baddate, as long as you have Node.js installed and access to a command-line of sorts, the instructions from the Readme should work. Unfortunately, I don't have access to a Windows machine, nor have I used one in quite a while, so I'm not sure how it works.

If somebody on Windows can let us know their experience, that'd be great!

**Comment by danburzo** [comment]
If anyone has access to a Windows machine: are the setup / usage info in the README sufficient for having percollate work on Windows? Do we need any extra information?

**Comment by danburzo** [comment]
I'm going to close this issue for now. Let's open a new issue when/if an issue with installing percollate on Windows crops up.
