### ISSUE TITLE
Add command `epub`

### ISSUE THREAD

**Issue by danburzo** [danburzo/percollate#8]

**Comment by j3r1ch0-2007** [comment]
Maybe checkout something like this [html-epub](https://www.npmjs.com/package/html-epub) or this [epub-gen](https://www.npmjs.com/package/epub-gen) to generate the epub files instead of PDF.

**Comment by danburzo** [comment]
Thank you for the suggestions! I'll have a look.

**Comment by j3r1ch0-2007** [comment]
Right, actually just sent a pull request for both commands (`epub` & `html`).

**Comment by danburzo** [comment]
Cool, I've answered on the PR.

**Comment by danburzo** [comment]
Fixed in https://github.com/danburzo/percollate/pull/98
