### ISSUE TITLE
Programmatic pdf creation html not rendered properly

### ISSUE THREAD

**Issue by yashha** [danburzo/percollate#82]
Does s.b. know what the reason is that the html is not properly rendered on programmatic pdf creation?
https://github.com/yashha/percollate-api/issues/1

**Comment by danburzo** [comment]
Looking at the source code, that seems to be indeed the problem. Here's how it's used in `cli.js`:

https://github.com/danburzo/percollate/blob/07fbcd82a4b398b7611818d78d417e47ac595192/cli.js#L7-L13
