### ISSUE TITLE
PDF: Fill in metadata

### ISSUE THREAD

**Issue by yashha** [danburzo/percollate#88]
Would be useful.
https://github.com/GoogleChrome/puppeteer/issues/3054

**Comment by yashha** [comment]
Maybe use this
https://github.com/Sobesednik/node-exiftool#readme

**Comment by danburzo** [comment]
It'd be great if Puppeteer supported this feature. I'm not 100% sure whether `node-exiftool` can be used to write PDF metadata or EXIF data for images embedded in PDF files.

**Comment by yashha** [comment]
Exiftool updates the exif/meta data of a file. I believe this is what I meant here.

I believe using this the right title would be displayed in the browser using my web api.
Also it would improve useability with programs like calibre.

Maybe we can suggest it in the puppeteer issue.

**Comment by danburzo** [comment]
That sounds good! If it works on your repo, I'll be glad to also merge it here.

**Comment by danburzo** [comment]
Thank you for this, @yashha. I think pdf-lib works well enough that we don't depend on Puppeteer to [add this feature](https://github.com/puppeteer/puppeteer/issues/3054).
