### ISSUE TITLE
Command `md` for Markdown

### ISSUE THREAD

**Issue by yashha** [danburzo/percollate#93]
Option to generate markdown file using a html2markdown library

**Comment by danburzo** [comment]
Once this gets merged in, `percollate html --output -` will print the processed HTML to `stdout`:

- https://github.com/danburzo/percollate/pull/151

This will allow the user to pipe the HTML into another tool, such as [trimd](https://github.com/danburzo/trimd), to process down to Markdown. Regardless of that, for better ergonomics, it would be good for Percollate to have its own `md` command.

Like in `trimd`, Markdown options can be namespaced to `--md.<option>=<value>`.
