### ISSUE TITLE
Missing picture in output file

### ISSUE THREAD

**Issue by rywiki** [danburzo/percollate#94]
When I use
`Cat urllist.txt | xargs percollate pdf --output Goodbye.pdf`
  When the pdf is output, som pictures will be lost. Most of this happens in the second half of the pdf file. I guess it might be that the website timed out for a centralized request that didn't return in time. Can you add a parameter setting timeout limit to the program or increase the request interval to avoid this situation.

translated by google

当我使用
`cat urllist.txt | xargs percollate pdf  --output Goodbye.pdf `
 输出pdf的时候，会出现图片遗失的情况。这种情况多数出现在pdf文件的后半部。我猜测可能是网站对于集中的请求没有及时返回而超时。能否为程序增加一下参数设置超时时间上限或者将请求间隔时间增加以避免这种情况。

**Comment by rywiki** [comment]
content of urllist.txt for test
http://www.ruanyifeng.com/blog/2018/04/weekly-issue-1.html
http://www.ruanyifeng.com/blog/2018/04/weekly-issue-2.html
http://www.ruanyifeng.com/blog/2018/05/weekly-issue-3.html
http://www.ruanyifeng.com/blog/2018/05/weekly-issue-4.html
http://www.ruanyifeng.com/blog/2018/05/weekly-issue-5.html
http://www.ruanyifeng.com/blog/2018/05/weekly-issue-6.html
http://www.ruanyifeng.com/blog/2018/06/weekly-issue-7.html
http://www.ruanyifeng.com/blog/2018/06/weekly-issue-8.html
http://www.ruanyifeng.com/blog/2018/06/weekly-issue-9.html
http://www.ruanyifeng.com/blog/2018/06/weekly-issue-10.html
http://www.ruanyifeng.com/blog/2018/06/weekly-issue-11.html
http://www.ruanyifeng.com/blog/2018/07/weekly-issue-12.html
http://www.ruanyifeng.com/blog/2018/07/weekly-issue-13.html
http://www.ruanyifeng.com/blog/2018/07/weekly-issue-14.html
http://www.ruanyifeng.com/blog/2018/07/weekly-issue-15.html
http://www.ruanyifeng.com/blog/2018/08/weekly-issue-16.html
http://www.ruanyifeng.com/blog/2018/08/weekly-issue-17.html
http://www.ruanyifeng.com/blog/2018/08/weekly-issue-18.html
http://www.ruanyifeng.com/blog/2018/08/weekly-issue-19.html
http://www.ruanyifeng.com/blog/2018/08/weekly-issue-20.html
http://www.ruanyifeng.com/blog/2018/09/weekly-issue-21.html
http://www.ruanyifeng.com/blog/2018/09/weekly-issue-22.html
http://www.ruanyifeng.com/blog/2018/09/weekly-issue-23.html
http://www.ruanyifeng.com/blog/2018/09/weekly-issue-24.html
http://www.ruanyifeng.com/blog/2018/10/weekly-issue-25.html
http://www.ruanyifeng.com/blog/2018/10/weekly-issue-26.html
http://www.ruanyifeng.com/blog/2018/10/weekly-issue-27.html
http://www.ruanyifeng.com/blog/2018/10/weekly-issue-28.html
http://www.ruanyifeng.com/blog/2018/11/weekly-issue-29.html
http://www.ruanyifeng.com/blog/2018/11/weekly-issue-30.html
http://www.ruanyifeng.com/blog/2018/11/weekly-issue-31.html
http://www.ruanyifeng.com/blog/2018/11/weekly-issue-32.html
http://www.ruanyifeng.com/blog/2018/11/weekly-issue-33.html
http://www.ruanyifeng.com/blog/2018/12/weekly-issue-34.html
http://www.ruanyifeng.com/blog/2018/12/weekly-issue-35.html
http://www.ruanyifeng.com/blog/2018/12/weekly-issue-36.html
http://www.ruanyifeng.com/blog/2018/12/weekly-issue-37.html
http://www.ruanyifeng.com/blog/2019/01/weekly-issue-38.html
http://www.ruanyifeng.com/blog/2019/01/weekly-issue-39.html
http://www.ruanyifeng.com/blog/2019/01/weekly-issue-40.html
http://www.ruanyifeng.com/blog/2019/01/weekly-issue-41.html
http://www.ruanyifeng.com/blog/2019/02/weekly-issue-42.html
http://www.ruanyifeng.com/blog/2019/02/weekly-issue-43.html
http://www.ruanyifeng.com/blog/2019/02/weekly-issue-44.html
http://www.ruanyifeng.com/blog/2019/03/weekly-issue-45.html
http://www.ruanyifeng.com/blog/2019/03/weekly-issue-46.html
http://www.ruanyifeng.com/blog/2019/03/weekly-issue-47.html
http://www.ruanyifeng.com/blog/2019/03/weekly-issue-48.html
http://www.ruanyifeng.com/blog/2019/03/weekly-issue-49.html
http://www.ruanyifeng.com/blog/2019/04/weekly-issue-50.html
http://www.ruanyifeng.com/blog/2019/04/weekly-issue-51.html
http://www.ruanyifeng.com/blog/2019/04/weekly-issue-52.html
http://www.ruanyifeng.com/blog/2019/04/weekly-issue-53.html
http://www.ruanyifeng.com/blog/2019/05/weekly-issue-54.html
http://www.ruanyifeng.com/blog/2019/05/weekly-issue-55.html
http://www.ruanyifeng.com/blog/2019/05/weekly-issue-56.html

**Comment by danburzo** [comment]
Hi there, thanks for the report. We've had problems with the timeout before, but in case the timeout is exceeded, you should get an error like here: #80.

I have not been able to test with your URL list, because for some reason it doesn't fetch any of the pages for me, but you could try running:

```bash
cat urllist.txt | xargs percollate pdf --output Goodbye.pdf --debug
```

to see a more detail list of requests, to check whether it's hanging on a request. Also, you could try exporting to individual PDFs with the command:

```bash
cat urllist.txt | xargs percollate pdf --individual
```

Hope this helps!

**Comment by rywiki** [comment]
Thank you for your reply.
I tried it with --debug, but the console outputs too much. I tried using `> out.log` but it didn't work. The output still lacks some images.
Use `--individual` to get the full result.
Thank you very much again.
@danburzo
